# Generated by Django 5.2.4 on 2025-07-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.CharField(default='unknown_user', max_length=100),
            preserve_default=False,
        ),
    ]
